baseURL = "https://naxxfish.net/"
description = "broadcast systems engineer, developer, photographer, maker and hobby collector"
languageCode = "en-gb"
theme = "terminal"
paginate = "5"


[params]
  author = "Chris Roberts"
  header = "Broadcast Systems Engineer, Developer, Maker and Hobby collector"
  logoUrl = "https://naxxfish.net/cropped-siteicon.png"
  twitter = "https://twitter.com/naxxfish/"
  instagram = "https://www.instagram.com/naxxfish/"
  github = "http://github.com/naxxfish"
  alumniOf = "University of Kent"
  birthplace = "London, UK"
  nationality = "British"
  jobTitle = "Product Manager"
  gender = "male"
  email = "chris@naxxfish.net"
  height = "173 cm"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "cropped-siteicon.png"
  description = "systems engineer, software developer, photographer, maker and hobby collector"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed/index"

[languages]
  [languages.en]
    languageName = "English"
    title = "naxxfish"
    subtitle = "systems engineer, software developer, photographer, maker and hobby collector"
    keywords = "software engineer developer tech"
    copyright = "Chris Roberts"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "naxxfish"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "wish-list"
        name = "Wish List"
        url = "/wish-list"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://www.github.com/naxxfish/"
      [[languages.en.menu.main]]
        identifier = "photography"
        name = "My Photography"
        url = "https://naxxfish.photography"